[2024-12-14T20:43:21.767-0500] {processor.py:186} INFO - Started process (PID=8253) to work on /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:43:21.768-0500] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14T20:43:21.768-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:43:21.768-0500] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:43:21.800-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:43:21.800-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14T20:43:21.800-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:43:21.800-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14T20:43:21.800-0500] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:43:21.830-0500] {processor.py:208} INFO - Processing /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-12-14T20:44:54.443-0500] {processor.py:186} INFO - Started process (PID=8423) to work on /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:44:54.444-0500] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14T20:44:54.444-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:44:54.444-0500] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:44:54.478-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:44:54.478-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14T20:44:54.478-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:44:54.478-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14T20:44:54.478-0500] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:44:54.508-0500] {processor.py:208} INFO - Processing /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-12-14T20:47:00.845-0500] {processor.py:186} INFO - Started process (PID=8645) to work on /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:47:00.845-0500] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14T20:47:00.846-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:47:00.846-0500] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:47:00.877-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:47:00.877-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14T20:47:00.877-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:47:00.877-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14T20:47:00.877-0500] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:47:00.906-0500] {processor.py:208} INFO - Processing /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2024-12-14T20:49:09.480-0500] {processor.py:186} INFO - Started process (PID=8863) to work on /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:49:09.481-0500] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14T20:49:09.482-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:49:09.482-0500] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:49:09.513-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:49:09.513-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14T20:49:09.513-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:49:09.513-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14T20:49:09.513-0500] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:49:09.543-0500] {processor.py:208} INFO - Processing /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-12-14T20:51:22.136-0500] {processor.py:186} INFO - Started process (PID=9079) to work on /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:51:22.136-0500] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14T20:51:22.137-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:51:22.136-0500] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:51:22.168-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:51:22.168-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14T20:51:22.168-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:51:22.168-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14T20:51:22.168-0500] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:51:22.197-0500] {processor.py:208} INFO - Processing /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2024-12-14T20:53:33.274-0500] {processor.py:186} INFO - Started process (PID=9335) to work on /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:53:33.275-0500] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14T20:53:33.275-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:53:33.275-0500] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:53:33.310-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:53:33.310-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14T20:53:33.310-0500] {logging_mixin.py:190} INFO - [2024-12-14T20:53:33.310-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14T20:53:33.311-0500] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14T20:53:33.342-0500] {processor.py:208} INFO - Processing /opt/anaconda3/envs/python310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
