[2024-12-19T17:45:24.256-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T17:45:24.260-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_python_etl_dag.read_the_csv_files manual__2024-12-19T22:45:22.045783+00:00 [queued]>
[2024-12-19T17:45:24.262-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_python_etl_dag.read_the_csv_files manual__2024-12-19T22:45:22.045783+00:00 [queued]>
[2024-12-19T17:45:24.262-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-19T17:45:24.268-0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): read_the_csv_files> on 2024-12-19 22:45:22.045783+00:00
[2024-12-19T17:45:24.270-0500] {standard_task_runner.py:72} INFO - Started process 83655 to run task
[2024-12-19T17:45:24.274-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_python_etl_dag', 'read_the_csv_files', 'manual__2024-12-19T22:45:22.045783+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/var/folders/jw/j912b4gd5xj0c7j8p3syth7r0000gn/T/tmpgzy816cf']
[2024-12-19T17:45:24.278-0500] {standard_task_runner.py:105} INFO - Job 87: Subtask read_the_csv_files
[2024-12-19T17:47:35.308-0500] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-19T17:47:35.313-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-19T17:47:35.322-0500] {process_utils.py:132} INFO - Sending 15 to group 83655. PIDs of all processes in the group: [83655]
[2024-12-19T17:47:35.323-0500] {process_utils.py:87} INFO - Sending the signal 15 to group 83655
[2024-12-19T17:47:35.331-0500] {process_utils.py:80} INFO - Process psutil.Process(pid=83655, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='17:45:24') (83655) terminated with exit code -15
