[2024-12-15T14:28:32.299-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T14:28:32.302-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_python_operators_dag.SampleA_function scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T14:28:32.304-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_python_operators_dag.SampleA_function scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T14:28:32.304-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-15T14:28:32.308-0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): SampleA_function> on 2024-12-14 00:00:00+00:00
[2024-12-15T14:28:32.310-0500] {standard_task_runner.py:72} INFO - Started process 42557 to run task
[2024-12-15T14:28:32.312-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_python_operators_dag', 'SampleA_function', 'scheduled__2024-12-14T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/python_operator_dag.py', '--cfg-path', '/var/folders/jw/j912b4gd5xj0c7j8p3syth7r0000gn/T/tmpzl121500']
[2024-12-15T14:28:32.314-0500] {standard_task_runner.py:105} INFO - Job 50: Subtask SampleA_function
[2024-12-15T14:28:32.327-0500] {task_command.py:467} INFO - Running <TaskInstance: executing_python_operators_dag.SampleA_function scheduled__2024-12-14T00:00:00+00:00 [running]> on host mac-4031.lan
[2024-12-15T14:28:32.346-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='venkatesh' AIRFLOW_CTX_DAG_ID='executing_python_operators_dag' AIRFLOW_CTX_TASK_ID='SampleA_function' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T00:00:00+00:00'
[2024-12-15T14:28:32.347-0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T14:28:32.353-0500] {logging_mixin.py:190} INFO - Inside sample A python function!
[2024-12-15T14:28:32.353-0500] {python.py:240} INFO - Done. Returned value was: None
[2024-12-15T14:28:32.354-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T14:28:32.355-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=executing_python_operators_dag, task_id=SampleA_function, run_id=scheduled__2024-12-14T00:00:00+00:00, execution_date=20241214T000000, start_date=20241215T192832, end_date=20241215T192832
[2024-12-15T14:28:32.375-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-15T14:28:32.382-0500] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-12-15T14:28:32.382-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
